import { base44ORM as base44 } from "../db/orm.ts";
import { client } from "../db/index.ts";


/**
 * Sends a WhatsApp payment-link message to a borrower for a loan account.
 *
 * The actual payment URL is generated by the lender's own payment-link provider
 * (Razorpay/Cashfree/Easebuzz) — we just pass it through here. If `payment_url`
 * isn't passed in, we construct a placeholder Razorpay-style link using the
 * client's configured base URL (if any) + the loan account ID.
 *
 * Wires through existing `sendWhatsAppTemplate` so all the messaging-config
 * lookup, unsubscribe checks, and OutreachLog rows are handled identically.
 *
 * Body: { client_id, loan_account_id, amount, ptp_date?, payment_url?,
 *         call_log_id?, channel? }
 * Output: { success, sent, channel, payment_url, message_id }
 *
 * Idempotency: marks the LoanAccount with metadata.last_payment_link_sent_at
 * so the same call doesn't fire twice.
 */

export default async function bfsiSendPaymentLink(c: any) {
  const req = c.req.raw || c.req;
  try {
    /* const base44 = ... */;
    const body = await c.req.json();
    const {
      client_id, loan_account_id, amount, ptp_date,
      payment_url, call_log_id, channel = 'whatsapp',
    } = body;

    if (!client_id || !loan_account_id) {
      return c.json({ data: { error: 'client_id and loan_account_id required' } }, 400);
    }

    const svc = base44.asServiceRole;
    const loanAccount = await svc.entities.LoanAccount.get(loan_account_id).catch(() => null);
    if (!loanAccount) return c.json({ data: { error: 'Loan account not found' } }, 404);
    if (loanAccount.client_id !== client_id) {
      return c.json({ data: { error: 'Loan account does not belong to client' } }, 403);
    }

    // Build the payment URL. If client has a base URL configured, use that;
    // otherwise default to a generic Razorpay-style placeholder.
    const client = await svc.entities.Client.get(client_id).catch(() => null);
    const bfsiCfg = client?.module_configs?.bfsi_suite || {};
    const baseUrl = bfsiCfg.payment_link_base_url || '';
    const resolvedUrl = payment_url
      || (baseUrl ? `${baseUrl.replace(/\/$/, '')}/${loanAccount.loan_id || loan_account_id}` : '')
      || `https://pay.example.com/loan/${loanAccount.loan_id || loan_account_id}`;

    const finalAmount = amount || loanAccount.emi_amount || loanAccount.outstanding_amount || 0;

    // Try to find a WhatsApp template tagged for BFSI payment links.
    // We look for an active template with intent === 'bfsi_payment_link' or name containing 'payment'.
    let templateId = bfsiCfg.payment_link_template_id || null;
    if (!templateId) {
      try {
        const templates = await svc.entities.MessageTemplate.filter({
          client_id, channel: 'whatsapp', is_active: true,
        });
        const candidate = templates.find(t =>
          t.intent === 'bfsi_payment_link' ||
          /payment|pay link|emi/i.test(t.name || '')
        );
        if (candidate) templateId = candidate.id;
      } catch (_) {}
    }

    // If no template configured, fall back to writing an OutreachLog so the
    // event is still tracked + retried, and return clearly to caller.
    if (!templateId) {
      await svc.entities.OutreachLog.create({
        client_id, lead_id: loan_account_id, call_log_id: call_log_id || null,
        channel: 'whatsapp', recipient_phone: loanAccount.phone,
        outreach_type: 'bfsi_payment_link',
        body: `Payment link for ₹${finalAmount}: ${resolvedUrl}${ptp_date ? ` • due ${ptp_date}` : ''}`,
        status: 'pending_template',
      }).catch(() => {});
      console.log(`[bfsiSendPaymentLink] No template — logged for manual follow-up. loan=${loan_account_id}`);
      return c.json({ data: {
        success: false,
        sent: false,
        reason: 'no_payment_link_template_configured',
        payment_url: resolvedUrl,
      } });
    }

    // Fire the WhatsApp template via the existing sender
    const variables = [
      loanAccount.customer_name || 'Customer',
      String(finalAmount),
      ptp_date || new Date().toISOString().slice(0, 10),
      resolvedUrl,
    ];
    const tRes = await base44.functions.invoke('sendWhatsAppTemplate', {
      client_id,
      template_id: templateId,
      to: loanAccount.phone,
      variables,
      lead_id: loan_account_id,
      call_log_id: call_log_id || null,
      outreach_type: 'bfsi_payment_link',
    });
    const sent = !!tRes?.data?.success;

    // Mirror onto loan account for audit
    if (sent) {
      await svc.entities.LoanAccount.update(loan_account_id, {
        metadata: {
          ...(loanAccount.metadata || {}),
          last_payment_link_sent_at: new Date().toISOString(),
          last_payment_link_url: resolvedUrl,
          last_payment_link_amount: finalAmount,
        },
      }).catch(() => {});
    }

    console.log(`[bfsiSendPaymentLink] loan=${loan_account_id} sent=${sent} url=${resolvedUrl}`);
    return c.json({ data: {
      success: sent,
      sent,
      channel,
      payment_url: resolvedUrl,
      amount: finalAmount,
      template_id: templateId,
    } });
  } catch (error) {
    console.error('[bfsiSendPaymentLink] error:', error);
    return c.json({ data: { error: error.message } }, 500);
  }

};