name: Trigger auto deployment for bolify

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bolify-AutoDeployTrigger-a0963786-edf2-482f-b484-d4633d07c2fa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BOLIFY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOLIFY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOLIFY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: codeastraregistry.azurecr.io
          registryUsername: ${{ secrets.BOLIFY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOLIFY_REGISTRY_PASSWORD }}
          containerAppName: bolify
          resourceGroup: vaani-ai-prod
          imageToBuild: codeastraregistry.azurecr.io/bolify:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


