name: Trigger auto deployment for bolify

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bolify-AutoDeployTrigger-00688b3d-bb3c-46e1-8b90-983e17f19aa1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BOLIFY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOLIFY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOLIFY_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: codeastraregistry.azurecr.io
          username: ${{ secrets.BOLIFY_REGISTRY_USERNAME }}
          password: ${{ secrets.BOLIFY_REGISTRY_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: codeastraregistry.azurecr.io/bolify:${{ github.sha }}
          file: Dockerfile

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: codeastraregistry.azurecr.io
          registryUsername: ${{ secrets.BOLIFY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOLIFY_REGISTRY_PASSWORD }}
          containerAppName: bolify
          resourceGroup: vaani-ai-prod
          imageToDeploy: codeastraregistry.azurecr.io/bolify:${{ github.sha }}

